 
version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - apt install python3
      - apt install python3-pip
  build:
    commands:
      - echo "Testando Build e Deploy"
#artifacts:
#  files:
#    - '*.py'
#    - '**/*'
#  discard-paths: no
#  name: backend-artifact
